# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=144)),
                ('name', models.CharField(max_length=144)),
                ('nombre', models.CharField(max_length=144)),
                ('en_slug', models.CharField(blank=True, max_length=144)),
                ('es_slug', models.CharField(blank=True, max_length=144)),
                ('context', models.TextField()),
                ('descripcion', models.TextField()),
                ('objectives', models.TextField()),
                ('objetivos', models.TextField()),
                ('benefits', models.TextField()),
                ('beneficios', models.TextField()),
                ('technology', models.TextField()),
                ('tecnologia', models.TextField()),
                ('process', models.TextField()),
                ('proceso', models.TextField()),
                ('slogan', models.TextField()),
                ('eslogan', models.TextField()),
                ('en_checklist', models.TextField()),
                ('es_checklist', models.TextField()),
                ('projects', models.TextField()),
                ('related', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background_image', models.ImageField(blank=True, height_field='background_image_width', upload_to='projects/backgrounds/', width_field='background_image_height')),
                ('background_image_height', models.IntegerField(blank=True, default=0)),
                ('background_image_width', models.IntegerField(blank=True, default=0)),
                ('large_image', models.ImageField(blank=True, height_field='large_image_width', upload_to='projects/images/large/', width_field='large_image_height')),
                ('large_image_height', models.IntegerField(blank=True, default=0)),
                ('large_image_width', models.IntegerField(blank=True, default=0)),
                ('short_image', models.ImageField(blank=True, height_field='short_image_width', upload_to='projects/images/short/', width_field='short_image_height')),
                ('short_image_height', models.IntegerField(blank=True, default=0)),
                ('short_image_width', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
